name: Terraform CI/CD

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Zip Lambda Function
        run: |
          cd lambda
          zip function.zip index.py

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan
        if: github.event_name == 'pull_request'

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
